name: pr1
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  sqflite: ^2.2.8+2
  path_provider: ^2.0.15 
  path: any
  pr1_models:
    path: packages/pr1_models
  pr1_repositories:
    path: packages/pr1_repositories
    
  flutter_web_plugins:
    sdk: flutter

  
dev_dependencies:
  flutter_test:
    sdk: flutter
 
  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  assets:
     - assets/img/img_home_page.jpg
     - assets/img/github.png
     - assets/img/wallet.png
     - assets/img/discord.png
     - assets/img/send.png
     - assets/img/man.png
     - assets/img/gamepad.png
     - assets/img/spotify.png

  fonts:
    - family: Sensal
      fonts:
        - asset: fonts/Sensal.ttf
    - family: Aref
      fonts:
        - asset: fonts/ArefRuqaaInk-Regular.ttf


