name: pr1
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  idb_shim: any
  http: any
  build_runner: any
  url_launcher: ^6.0.0
  flutter_web_auth: any
  spotify_sdk: ^2.0.0
  flutter_widget_from_html_core: any
  fwfh_webview: ^0.7.0



  
dev_dependencies:
  idb_sqflite: any
  build_web_compilers: any
  


  flutter_web_plugins:
    sdk: flutter
    
  flutter_test:
    sdk: flutter
 
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
     - assets/img/img_home_page.jpg
     - assets/img/github.png
     - assets/img/wallet.png
     - assets/img/discord.png
     - assets/img/send.png
     - assets/img/man.png
     - assets/img/gamepad.png
     - assets/img/chat.png
     - assets/img/spotify.png
     - assets/img/info.png
  fonts:
    - family: Sensal
      fonts:
        - asset: fonts/Sensal.ttf
    - family: Aref
      fonts:
        - asset: fonts/ArefRuqaaInk-Regular.ttf


